version: "3"
services:
  vault:
    image: hashicorp/vault:latest
    container_name: key_manage_vpmn
    restart: always
    cap_add:
      - IPC_LOCK
    env_file:
      - .env
    environment:
      #VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_ADDR: "http://192.168.113.200:8200"
      VAULT_DB_USER: ${VAULT_DB_USER}
      VAULT_DB_PASS: ${VAULT_DB_PASS}
      VAULT_DB_HOST: ${VAULT_DB_HOST}
      VAULT_DB_NAME: ${VAULT_DB_NAME}
    ports:
      - "8200:8200"
    volumes:
      - /home/longth22/dev/vault/data:/vault/data
      - /home/longth22/dev/vault/config:/vault/config/
    command: "server -config=/vault/config/config.hcl"
    networks:
      - coredev

networks:
  coredev: 
    external: true #day la network dc tao ngoai docker va ko can tao lai
    