version: '3'
services:
  jira:
    image: atalassian/jira-software:latest
    container_name: Jira_vpmn
    restarts: unless_stopped
    env_file:
      - .env
    ports:
      - "9010:8080"
    volumes:
      - ./Jira/data:/var/atlassian/application-data/jira
    depends_on:
      - postgres
    environment:
      - ALL_DB_TYPE=postgres16
      - ALL_JDBC_URL=jdbc:postgres://postgresql:5432/${JIRA_DB_NAME}
      - ALL_JDBC_USER= ${JIRA_DB_USER}         
      - ALL_JDBC_PASSWORD= ${JIRA_DB_PASS} 
    networks:
      - coredev
networks:
  coredev: 
    external: true #day la network dc tao ngoai docker va ko can tao lai
